Add files via upload
Yandex-Practicum/go-first-floor-sprint-five pull request #5
Opened 2023-11-19 14:24 UTC by goncharovaleksei

work version

2023-11-24 10:09 UTC, robotomize requested changes
Хорошо, но требуются доработки

2023-11-24 10:09 UTC, robotomize commented on main.go
> +	return t.distance() / t.Duration.Hours()
Не хватает проверки Duration на 0

2023-11-24 10:09 UTC, robotomize commented on main.go
> +	return float64(s.LengthPool) * float64(s.CountPool) / MInKm / s.Duration.Hours()
Не хватает проверки Duration на 0

2023-11-24 10:09 UTC, robotomize commented on main.go
> +	return s.Training.TrainingInfo()
Тут, когда мы отдаем структуру InfoMessage у нас будет расчитана скорость базовых тренировок. Нам нужно, чтобы в InfoMessage была посчитана скорость плавания

2023-11-24 10:09 UTC, robotomize commented on main.go
> +	return (CaloriesWeightMultiplier * w.Weight + (math.Pow(w.meanSpeed()*1000/3600, 2.0) / w.Height) * CaloriesSpeedHeightMultiplier*w.Weight) * w.Duration.Hours() * MinInHours
Тут ошибка в формуле расчета калорий. 

- Рост указывается в сантимерах, в формуле в метрах, используй константу в коде для преобразования
- Формула скорости не очень точна. Для первода в м/c авторы предложили использовать константу KmHInSec. Используй ее для получения скорости
В результате, результат для ходьбы должны быть

> Тип тренировки: Ходьба
Длительность: 225 мин
Дистанция: 13.00 км.
Ср. скорость: 3.47 км/ч
Потрачено ккал: 947.82

2023-12-01 11:05 UTC, goncharovaleksei commented
поправил по замечаниям

2023-12-01 11:05 UTC, closed without merging